<?php

namespace AttedanceManagement\UserBundle\Repository;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
