<?php

namespace AttedanceManagement\UserBundle\Repository;

use AttedanceManagement\UserBundle\Entity\User;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassGroupRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * Find all group that belong teacher
     *
     * @param User $teacher
     *
     * @return QueryBuilder
     */
    public function findByTeacher(User $teacher)
    {
        $qb = $this->createQueryBuilder('g');
        if ($teacher->hasRole('ROLE_ADMIN')) {
            $subjectQuery = $this->getEntityManager()->getRepository('AttedanceManagementUserBundle:SubjectGroup')->getAllGroups();
        } else {
            $subjectQuery = $this->getEntityManager()->getRepository('AttedanceManagementUserBundle:SubjectGroup')->findGroupByTeacher($teacher);
            $qb->setParameter('teacher', $teacher);
        }
        $qb->where(
             $qb
            ->expr()
            ->in(
                'g.id',
                $subjectQuery->getDQL()
            )
        );

        $qb->orderBy('g.id', 'DESC');

        return $qb;

    }
}
