<?php

namespace AttedanceManagement\UserBundle\Repository;

use AttedanceManagement\UserBundle\Entity\ClassGroup;
use AttedanceManagement\UserBundle\Entity\Subject;
use AttedanceManagement\UserBundle\Entity\User;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all student by filter form
     *
     * @param User $teacher
     * @param Subject|null $subject
     * @param ClassGroup|null $classGroup
     *
     * @return QueryBuilder
     */
    public function findByFilter(
        User $teacher,
        $subject,
        $classGroup
    ) {
        $classGroupQuery = $this->getEntityManager()->getRepository('AttedanceManagementUserBundle:SubjectGroup')->findByFilter($teacher, $subject, $classGroup);
        $qb = $this->createQueryBuilder('s');
        $qb->where(
             $qb
            ->expr()
            ->in(
                's.classGroup',
                $classGroupQuery->getDQL()
            )
        );

        if (!$teacher->hasRole('ROLE_ADMIN')) {
            $qb->setParameter('teacher', $teacher);
        }
        if (!empty($subject)) {
            $qb->setParameter('subject', $subject);
        }
        if (!empty($classGroup)) {
            $qb->setParameter('group', $classGroup);
        }

        $qb->orderBy('s.id', 'DESC');

        return $qb;
    }
}
