<?php

namespace AttedanceManagement\UserBundle\Repository;

/**
 * SubjectGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
