<?php

namespace AttedanceManagement\UserBundle\Repository;

use AttedanceManagement\UserBundle\Entity\User;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all subject that belong teacher
     *
     * @param User $teacher
     *
     * @return QueryBuilder
     */
    public function findByTeacher(User $teacher)
    {
        $qb = $this->createQueryBuilder('s');
        if ($teacher->hasRole('ROLE_ADMIN')) {
            $subjectQuery = $this->getEntityManager()->getRepository('AttedanceManagementUserBundle:SubjectGroup')->getAllSubject();
        } else {
            $subjectQuery = $this->getEntityManager()->getRepository('AttedanceManagementUserBundle:SubjectGroup')->findSubjectByTeacher($teacher);
            $qb->setParameter('teacher', $teacher);
        }
        $qb->where(
             $qb
            ->expr()
            ->in(
                's.id',
                $subjectQuery->getDQL()
            )
        );

        $qb->orderBy('s.id', 'DESC');

        return $qb;

    }
}
