<?php

namespace AttedanceManagement\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all user that have role teacher
     *
     * @return QueryBuilder
     */
    public function findAllTeacher()
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.roles LIKE :teacher')
            ->setParameter('teacher', '%"ROLE_TEACHER"%')
            ->orderBy('u.id', 'DESC');

        return $qb;
        
    }
}
