imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    use_microseconds: false
    handlers:
        main:
            type: rotating_file
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level: "%app_log_level%"
            max_files: "%app_log_max_files%"
