---
- name: PostgreSQL server and client
  apt: name=postgresql-9.3,libpq-dev,python-psycopg2

- name: PostgreSQL database user
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_user: name={{ DBUSER }} password={{ DBPASSWORD }}

- name: PostgreSQL database init
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_db: name={{ DBNAME }} owner={{ DBUSER }}