---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars:
    APPDIR: "/vagrant/{{ APPNAME }}"
    APPWEBROOT: "{{ APPDIR }}/web"
    when: APPNAME is defined
    APPCOMMONDIR: "/vagrant"
    APPUSER: "vagrant"

  pre_tasks:
    - name: check last APT update time
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - apache
    - "{{ DBTYPE }}"
    # - hhvm
    - php
    - git
    - symfony
    - { role: webapp, when: APPNAME is defined }
    - { role: webapp-container, when: APPNAME is defined }
    - vagrantbox
