---
- name: initialize application via composer.phar
  become: true
  become_user: vagrant
  become_method: sudo
  command: creates={{ APPDIR }}/
    /vagrant/composer.phar create-project --no-interaction --quiet symfony/framework-standard-edition {{ APPDIR }}
