---
- name: initialize application via symfony.phar
  become: true
  become_user: vagrant
  become_method: sudo
  shell: creates={{ APPDIR }}/ chdir=/tmp
    symfony new --no-interaction --quiet {{ APPNAME }}-install
    && mv {{ APPNAME }}-install {{ APPDIR }}

